name: Build and Deploy Blazor WebAssembly App

on:
  push:
    branches:
      - main  # Branche que vous utilisez pour le déploiement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'  # Version de .NET que vous utilisez

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -o build_output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build_output/wwwroot
